services:
  saleswork:
    build: .
    image: sales_integration:latest
    command: ["python", "manager.py", "saleswork"]
    volumes:
      - /root/sales_integration/envs/.env.sayonar:/sales_integration/.env.sayonar:ro
      - /root/sales_integration/envs/.env.borjomi:/sales_integration/.env.borjomi:ro
      - /root/sales_integration/envs/.env.royalstar:/sales_integration/.env.royalstar:ro
    restart: "no"

  monolit:
    image: sales_integration:latest
    command: ["python", "manager.py", "monolit"]
    volumes:
      - /root/sales_integration/envs/.env.sayonar:/sales_integration/.env.sayonar:ro
      - /root/sales_integration/envs/.env.borjomi:/sales_integration/.env.borjomi:ro
      - /root/sales_integration/envs/.env.royalstar:/sales_integration/.env.royalstar:ro
    restart: "no"
